package com.webhookplatform.webhook.dashboard;

import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Instant;
import java.util.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.webhookplatform.webhook.application.ApplicationService;
import com.webhookplatform.webhook.application.ApplicationNotFoundException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
class DashboardService {
    private static final int DEFAULT_SIZE=25, MAX_SIZE=100;
    private final JdbcTemplate jdbc; private final ApplicationService applications; private final Clock clock; private final ObjectMapper json;
    DashboardService(JdbcTemplate jdbc, ApplicationService applications, Clock clock, ObjectMapper json) { this.jdbc=jdbc; this.applications=applications; this.clock=clock; this.json=json; }
    private void owned(UUID app, UUID user) { applications.requireOwnedApplication(app, user); }
    @Transactional(readOnly=true) DashboardSummaryResponse summary(UUID app, UUID user) {
        owned(app,user); Instant since=clock.instant().minusSeconds(86400);
        return jdbc.queryForObject("""
                SELECT (SELECT count(*) FROM webhook_events e WHERE e.application_id=?) events_total,
                  (SELECT count(*) FROM webhook_events e WHERE e.application_id=? AND e.created_at>=?) events_24,
                  count(d.*) FILTER (WHERE d.status='PENDING') pending, count(d.*) FILTER (WHERE d.status='PROCESSING') processing,
                  count(d.*) FILTER (WHERE d.status='RETRY_SCHEDULED') retrying, count(d.*) FILTER (WHERE d.status='DELIVERED') delivered,
                  count(d.*) FILTER (WHERE d.status='FAILED') failed, count(d.*) FILTER (WHERE d.status='FAILED' AND d.updated_at>=?) recent
                FROM webhook_deliveries d JOIN webhook_events e ON e.id=d.event_id WHERE e.application_id=?
                """, (rs,n)->new DashboardSummaryResponse(new EventCounts(rs.getLong(1),rs.getLong(2)),new DeliveryCounts(rs.getLong(3),rs.getLong(4),rs.getLong(5),rs.getLong(6),rs.getLong(7)),rs.getLong(8)),app,app,java.sql.Timestamp.from(since),java.sql.Timestamp.from(since),app);
    }
    @Transactional(readOnly=true) CursorPage<EventListItem> events(UUID app, UUID user,String cursor,Integer size,String type,String source,Instant from,Instant to) {
        owned(app,user); Page p=page(cursor,size,from,to); StringBuilder q=new StringBuilder("SELECT e.id,e.source_event_id,e.event_type,e.created_at,count(d.id),count(d.id) FILTER(WHERE d.status='DELIVERED'),count(d.id) FILTER(WHERE d.status='FAILED'),count(d.id) FILTER(WHERE d.status='RETRY_SCHEDULED') FROM webhook_events e LEFT JOIN webhook_deliveries d ON d.event_id=e.id WHERE e.application_id=?"); List<Object>a=new ArrayList<>(List.of(app)); filters(q,a,"e",type,source,null,p); q.append(" GROUP BY e.id,e.source_event_id,e.event_type,e.created_at ORDER BY e.created_at DESC,e.id DESC LIMIT ?"); a.add(p.limit()+1); List<EventListItem> rows=jdbc.query(q.toString(),(rs,n)->new EventListItem((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getTimestamp(4).toInstant(),rs.getLong(5),rs.getLong(6),rs.getLong(7),rs.getLong(8)),a.toArray()); return page(rows,EventListItem::createdAt,EventListItem::id,p);
    }
    @Transactional(readOnly=true) EventDetailResponse event(UUID app,UUID id,UUID user) { owned(app,user); return jdbc.query("SELECT e.id,e.source_event_id,e.event_type,e.created_at,e.payload::text,count(d.id),count(d.id) FILTER(WHERE d.status='DELIVERED'),count(d.id) FILTER(WHERE d.status='FAILED'),count(d.id) FILTER(WHERE d.status='RETRY_SCHEDULED') FROM webhook_events e LEFT JOIN webhook_deliveries d ON d.event_id=e.id WHERE e.application_id=? AND e.id=? GROUP BY e.id",rs->{if(!rs.next())throw new ApplicationNotFoundException(); try{return new EventDetailResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getTimestamp(4).toInstant(),json.readTree(rs.getString(5)),rs.getLong(6),rs.getLong(7),rs.getLong(8),rs.getLong(9));}catch(Exception x){throw new IllegalStateException(x);}},app,id); }
    @Transactional(readOnly=true) CursorPage<DeliveryListItem> deliveries(UUID app,UUID user,String cursor,Integer size,String status,UUID endpoint,String type,Instant from,Instant to) { owned(app,user); Page p=page(cursor,size,from,to); if(status!=null&&!Set.of("PENDING","PROCESSING","RETRY_SCHEDULED","DELIVERED","FAILED").contains(status))throw new DashboardQueryException("Invalid delivery status."); StringBuilder q=new StringBuilder("SELECT d.id,e.id,e.event_type,ep.id,ep.name,d.status,d.next_retry_at,count(a.id),la.attempt_number,la.status,la.http_status_code,la.error_code,d.created_at,d.updated_at FROM webhook_deliveries d JOIN webhook_events e ON e.id=d.event_id JOIN webhook_endpoints ep ON ep.id=d.endpoint_id LEFT JOIN webhook_delivery_attempts a ON a.delivery_id=d.id LEFT JOIN LATERAL(SELECT attempt_number,status,http_status_code,error_code FROM webhook_delivery_attempts x WHERE x.delivery_id=d.id ORDER BY attempt_number DESC LIMIT 1) la ON true WHERE e.application_id=?"); List<Object>a=new ArrayList<>(List.of(app)); filters(q,a,"d",type,null,endpoint,p); if(status!=null){q.append(" AND d.status=?");a.add(status);} q.append(" GROUP BY d.id,e.id,e.event_type,ep.id,ep.name,la.attempt_number,la.status,la.http_status_code,la.error_code ORDER BY d.created_at DESC,d.id DESC LIMIT ?");a.add(p.limit()+1); List<DeliveryListItem> rows=jdbc.query(q.toString(),(rs,n)->new DeliveryListItem((UUID)rs.getObject(1),(UUID)rs.getObject(2),rs.getString(3),(UUID)rs.getObject(4),rs.getString(5),rs.getString(6),instant(rs,7),rs.getLong(8),rs.getObject(9)==null?null:new AttemptSummary(rs.getInt(9),rs.getString(10),rs.getObject(11,Integer.class),rs.getString(12)),rs.getTimestamp(13).toInstant(),rs.getTimestamp(14).toInstant()),a.toArray()); return page(rows,DeliveryListItem::createdAt,DeliveryListItem::id,p); }
    @Transactional(readOnly=true) DeliveryDetailResponse delivery(UUID app,UUID id,UUID user) { owned(app,user); return jdbc.query("SELECT d.id,d.status,e.id,e.source_event_id,e.event_type,e.created_at,ep.id,ep.name,ep.url,d.target_url,d.next_retry_at,d.created_at,d.updated_at FROM webhook_deliveries d JOIN webhook_events e ON e.id=d.event_id JOIN webhook_endpoints ep ON ep.id=d.endpoint_id WHERE e.application_id=? AND d.id=?",rs->{if(!rs.next())throw new ApplicationNotFoundException();return new DeliveryDetailResponse((UUID)rs.getObject(1),rs.getString(2),new EventReference((UUID)rs.getObject(3),rs.getString(4),rs.getString(5),rs.getTimestamp(6).toInstant()),new EndpointReference((UUID)rs.getObject(7),rs.getString(8),safeUrl(rs.getString(9))),safeUrl(rs.getString(10)),instant(rs,11),rs.getTimestamp(12).toInstant(),rs.getTimestamp(13).toInstant());},app,id); }
    @Transactional(readOnly=true) List<AttemptItem> attempts(UUID app,UUID delivery,UUID user) { owned(app,user); if(jdbc.queryForObject("SELECT count(*) FROM webhook_deliveries d JOIN webhook_events e ON e.id=d.event_id WHERE e.application_id=? AND d.id=?",Long.class,app,delivery)==0)throw new ApplicationNotFoundException();return jdbc.query("SELECT id,attempt_number,status,started_at,completed_at,duration_ms,http_status_code,error_code FROM webhook_delivery_attempts WHERE delivery_id=? ORDER BY attempt_number ASC",(rs,n)->new AttemptItem((UUID)rs.getObject(1),rs.getInt(2),rs.getString(3),rs.getTimestamp(4).toInstant(),instant(rs,5),rs.getObject(6,Long.class),rs.getObject(7,Integer.class),rs.getString(8)),delivery); }
    private void filters(StringBuilder q,List<Object>a,String alias,String type,String source,UUID endpoint,Page p){if(type!=null){q.append(" AND "+(alias.equals("e")?"e.event_type":"e.event_type")+"=?");a.add(type);}if(source!=null){q.append(" AND e.source_event_id=?");a.add(source);}if(endpoint!=null){q.append(" AND d.endpoint_id=?");a.add(endpoint);}if(p.from!=null){q.append(" AND "+alias+".created_at>=?");a.add(java.sql.Timestamp.from(p.from));}if(p.to!=null){q.append(" AND "+alias+".created_at<=?");a.add(java.sql.Timestamp.from(p.to));}if(p.cursor!=null){q.append(" AND ("+alias+".created_at<? OR ("+alias+".created_at=? AND "+alias+".id<?))");a.add(java.sql.Timestamp.from(p.cursor.at));a.add(java.sql.Timestamp.from(p.cursor.at));a.add(p.cursor.id);}}
    private Page page(String c,Integer s,Instant from,Instant to){if(from!=null&&to!=null&&from.isAfter(to))throw new DashboardQueryException("createdFrom must not be after createdTo.");int n=s==null?DEFAULT_SIZE:s;if(n<1||n>MAX_SIZE)throw new DashboardQueryException("size must be between 1 and 100.");return new Page(n,decode(c),from,to);}
    private Cursor decode(String value){if(value==null)return null;try{String[]x=new String(Base64.getUrlDecoder().decode(value),StandardCharsets.UTF_8).split("\\|",-1);return x.length==2?new Cursor(Instant.parse(x[0]),UUID.fromString(x[1])):bad();}catch(Exception e){throw new DashboardQueryException("Invalid cursor.");}}
    private Cursor bad(){throw new DashboardQueryException("Invalid cursor.");} private String encode(Instant at,UUID id){return Base64.getUrlEncoder().withoutPadding().encodeToString((at+"|"+id).getBytes(StandardCharsets.UTF_8));} private <T> CursorPage<T> page(List<T> rows,java.util.function.Function<T,Instant> at,java.util.function.Function<T,UUID> id,Page p){boolean more=rows.size()>p.limit;List<T> out=more?rows.subList(0,p.limit):rows;if(out.isEmpty())return new CursorPage<>(out,null);T last=out.get(out.size()-1);return new CursorPage<>(out,more?encode(at.apply(last),id.apply(last)):null);} private Instant instant(java.sql.ResultSet r,int i)throws java.sql.SQLException{var x=r.getTimestamp(i);return x==null?null:x.toInstant();} private String safeUrl(String raw){try{URI u=URI.create(raw);return new URI(u.getScheme(),null,u.getHost(),u.getPort(),u.getPath(),null,null).toString();}catch(Exception e){return null;}} private record Cursor(Instant at,UUID id){} private record Page(int limit,Cursor cursor,Instant from,Instant to){}
}
