import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { ApiError, dashboardApi, type DeliveryListItem, type DeliveryStatus } from '../api/dashboard-api'
import { DeliveryStatusBadge, ErrorCodeDisplay, HttpStatusDisplay } from '../components/status/StatusBadges'
import { EmptyState, ErrorState, LoadingState, NotFoundState } from '../components/states/States'
import { compactDateTime, dateTime, fromDateTimeLocalValue, shortId, toDateTimeLocalValue } from '../lib/format'
import { Button } from '../components/ui/Button'

const filterKeys = ['status', 'endpointId', 'eventType', 'createdFrom', 'createdTo'] as const
type FilterKey = typeof filterKeys[number]
const statuses: DeliveryStatus[] = ['PENDING', 'PROCESSING', 'RETRY_SCHEDULED', 'DELIVERED', 'FAILED']

export function DeliveriesPage() {
  const { applicationId = '' } = useParams(); const [search, setSearch] = useSearchParams()
  const filters = Object.fromEntries(filterKeys.map((key) => [key, search.get(key) ?? ''])) as Record<FilterKey, string>
  const identity = `${applicationId}:${search.toString()}`; const [draft, setDraft] = useState(filters); const [items, setItems] = useState<DeliveryListItem[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [moreLoading, setMoreLoading] = useState(false); const [error, setError] = useState<Error | null>(null); const [retryVersion, setRetryVersion] = useState(0); const requestId = useRef(0); const loadMoreController = useRef<AbortController | null>(null)
  useLayoutEffect(() => { loadMoreController.current?.abort(); requestId.current += 1; setLoading(true); setMoreLoading(false); setError(null); setItems([]); setCursor(null) }, [identity])
  useEffect(() => setDraft(filters), [identity])
  useEffect(() => { const controller = new AbortController(); const id = ++requestId.current; loadMoreController.current?.abort(); setLoading(true); setError(null); setItems([]); setCursor(null); void dashboardApi.deliveries(applicationId, { ...filters, size: 25 }, controller.signal).then((page) => { if (id === requestId.current) { setItems(page.items); setCursor(page.nextCursor) } }).catch((reason: unknown) => { if (!controller.signal.aborted && id === requestId.current) setError(reason instanceof Error ? reason : new Error('Request failed')) }).finally(() => { if (id === requestId.current) setLoading(false) }); return () => controller.abort() }, [applicationId, identity, retryVersion])
  const loadMore = useCallback(() => { if (!cursor || moreLoading) return; const controller = new AbortController(); loadMoreController.current = controller; const id = ++requestId.current; setMoreLoading(true); setError(null); void dashboardApi.deliveries(applicationId, { ...filters, cursor, size: 25 }, controller.signal).then((page) => { if (id === requestId.current) { setItems((previous) => [...previous, ...page.items.filter((item) => !previous.some((old) => old.id === item.id))]); setCursor(page.nextCursor) } }).catch((reason: unknown) => { if (!controller.signal.aborted && id === requestId.current) setError(reason instanceof Error ? reason : new Error('Request failed')) }).finally(() => { if (id === requestId.current) setMoreLoading(false) }) }, [applicationId, cursor, filters, moreLoading])
  function apply() { const next = new URLSearchParams(); if (draft.status) next.set('status', draft.status); if (draft.endpointId) next.set('endpointId', draft.endpointId); if (draft.eventType) next.set('eventType', draft.eventType); const from = fromDateTimeLocalValue(draft.createdFrom); const to = fromDateTimeLocalValue(draft.createdTo); if (from) next.set('createdFrom', from); if (to) next.set('createdTo', to); setSearch(next, { replace: true }) }
  if (loading) return <LoadingState label="Loading deliveries" />; if (error instanceof ApiError && error.status === 404) return <NotFoundState title="Application not found" />; if (error) return <ErrorState message={error.message} onRetry={() => setRetryVersion((version) => version + 1)} />
  return <section className="page-stack"><div className="page-heading"><div><p className="eyebrow">Observability</p><h1>Deliveries</h1><p>Durable outbound webhook responsibilities and current status.</p></div></div><form className="filter-toolbar" onSubmit={(event) => { event.preventDefault(); apply() }}><label>Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="">All statuses</option>{statuses.map((status) => <option value={status} key={status}>{status}</option>)}</select></label><label>Endpoint ID<input value={draft.endpointId} onChange={(event) => setDraft({ ...draft, endpointId: event.target.value })} /></label><label>Event type<input value={draft.eventType} onChange={(event) => setDraft({ ...draft, eventType: event.target.value })} /></label><label>From<input type="datetime-local" value={toDateTimeLocalValue(draft.createdFrom)} onChange={(event) => setDraft({ ...draft, createdFrom: event.target.value })} /></label><label>To<input type="datetime-local" value={toDateTimeLocalValue(draft.createdTo)} onChange={(event) => setDraft({ ...draft, createdTo: event.target.value })} /></label><Button type="submit">Apply filters</Button></form>{items.length === 0 ? <EmptyState title={search.size ? 'No deliveries match these filters' : 'No deliveries yet'} detail="Deliveries appear after an event matches an active endpoint subscription." /> : <div className="table-scroll"><table><thead><tr><th>Delivery</th><th>Event</th><th>Endpoint</th><th>Status</th><th>Attempts / last result</th><th>Next retry</th><th>Created</th></tr></thead><tbody>{items.map((delivery) => <tr key={delivery.id}><td><Link to={`/app/${applicationId}/deliveries/${delivery.id}`} className="mono">{shortId(delivery.id)}</Link></td><td className="mono">{delivery.eventType}<small>{shortId(delivery.eventId)}</small></td><td>{delivery.endpointName}</td><td><DeliveryStatusBadge status={delivery.status} /></td><td>{delivery.attemptCount}<small>{delivery.lastAttempt && <><HttpStatusDisplay status={delivery.lastAttempt.httpStatusCode} /> <ErrorCodeDisplay code={delivery.lastAttempt.errorCode} /></>}</small></td><td>{delivery.nextRetryAt ? dateTime(delivery.nextRetryAt) : '—'}</td><td>{compactDateTime(delivery.createdAt)}</td></tr>)}</tbody></table></div>}{cursor && <Button variant="secondary" disabled={moreLoading} onClick={loadMore}>{moreLoading ? 'Loading…' : 'Load more'}</Button>}</section>
}
