import { useCallback, useRef, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ApiError, dashboardApi, type WebhookEndpoint } from '../api/dashboard-api'
import { Button } from '../components/ui/Button'
import { Dialog } from '../components/ui/Dialog'
import { SecretRevealDialog } from '../components/ui/SecretRevealDialog'
import { EmptyState, ErrorState, LoadingState, NotFoundState } from '../components/states/States'
import { useResource } from '../lib/useResource'

export function EndpointsPage() { const { applicationId = '' } = useParams(); return <EndpointsContent key={applicationId} applicationId={applicationId} /> }
function EndpointsContent({ applicationId }: { applicationId: string }) {
 const resource = useResource(`endpoints:${applicationId}`, useCallback((signal: AbortSignal) => dashboardApi.endpoints(applicationId, signal), [applicationId])); const [createOpen,setCreateOpen]=useState(false); const [secret,setSecret]=useState<string|null>(null); const createRef=useRef<HTMLButtonElement>(null)
 if(resource.loading)return <LoadingState label="Loading endpoints"/>; if(resource.error instanceof ApiError&&resource.error.status===404)return <NotFoundState title="Application not found"/>; if(resource.error||!resource.data)return <ErrorState message={resource.error?.message??'Request failed'} onRetry={resource.reload}/>
 return <section className="page-stack credential-page"><div className="page-heading"><div><p className="eyebrow">Webhook configuration</p><h1>Endpoints</h1><p>Configure destinations that receive this application’s webhook events.</p></div><Button ref={createRef} onClick={()=>setCreateOpen(true)}>Add endpoint</Button></div>{resource.data.length===0?<EmptyState title="No endpoints yet" detail="Add an HTTPS webhook destination to start configuring subscriptions."/>:<div className="panel table-scroll"><table><thead><tr><th>Name</th><th>URL</th><th>Status</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>{resource.data.map(endpoint=><tr key={endpoint.id}><td><Link className="table-link" to={`/app/${applicationId}/endpoints/${endpoint.id}`}>{endpoint.name}</Link></td><td><code className="mono-inline">{endpoint.url}</code></td><td><span className={`credential-status credential-status--${endpoint.status.toLowerCase()}`}>{endpoint.status === 'ACTIVE'?'Active':'Disabled'}</span></td><td><Link className="text-action" to={`/app/${applicationId}/endpoints/${endpoint.id}`}>Configure</Link></td></tr>)}</tbody></table></div>}{createOpen&&<CreateEndpointDialog applicationId={applicationId} returnFocusRef={createRef} onDismiss={()=>setCreateOpen(false)} onCreated={(endpoint, raw)=>{resource.update(current=>[endpoint,...(current??[])]);setCreateOpen(false);setSecret(raw)}}/>}{secret&&<SecretRevealDialog title="Signing secret created" secret={secret} description="Copy this signing secret now. It is shown only once." onDismiss={()=>setSecret(null)} returnFocusRef={createRef}/>}</section>
}
function CreateEndpointDialog({applicationId,onDismiss,onCreated,returnFocusRef}:{applicationId:string;onDismiss:()=>void;onCreated:(endpoint:WebhookEndpoint,secret:string)=>void;returnFocusRef:React.RefObject<HTMLElement|null>}){const nameRef=useRef<HTMLInputElement>(null);const inFlight=useRef(false);const[name,setName]=useState('');const[url,setUrl]=useState('');const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(inFlight.current)return;const normalizedName=name.trim(),normalizedUrl=url.trim();try{const parsed=new URL(normalizedUrl);if(!/^https?:$/.test(parsed.protocol))throw new Error()}catch{setError('Enter an absolute HTTP or HTTPS URL.');return}if(!normalizedName||normalizedName.length>120||normalizedUrl.length>2048){setError('Check the endpoint name and URL.');return}inFlight.current=true;setBusy(true);try{const created=await dashboardApi.createEndpoint(applicationId,{name:normalizedName,url:normalizedUrl});const{signingSecret,...endpoint}=created;onCreated(endpoint,signingSecret)}catch(err){setError(err instanceof ApiError&&err.code==='INVALID_ENDPOINT_URL'?'The endpoint URL is not allowed.':'We could not add the endpoint. Try again.')}finally{inFlight.current=false;setBusy(false)}}return <Dialog title="Add endpoint" onDismiss={busy?()=>undefined:onDismiss} returnFocusRef={returnFocusRef} initialFocusRef={nameRef}><form className="application-form" onSubmit={e=>void submit(e)} noValidate><label className="form-field" htmlFor="endpoint-name"><span>Name</span><input ref={nameRef} id="endpoint-name" value={name} placeholder="Production webhook" onChange={e=>{setName(e.target.value);setError(null)}}/></label><label className="form-field" htmlFor="endpoint-url"><span>Destination URL</span><input id="endpoint-url" type="url" value={url} placeholder="https://example.com/webhooks" onChange={e=>{setUrl(e.target.value);setError(null)}}/></label><p className="form-helper">The backend applies the final URL security policy.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="application-form-actions"><Button variant="secondary" disabled={busy} onClick={onDismiss}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Adding…':'Add endpoint'}</Button></div></form></Dialog>}
