import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, expect, it, vi } from 'vitest'
import { EndpointDetailPage } from './EndpointDetailPage'

const endpoint={id:'endpoint-1',name:'Primary endpoint',url:'https://example.com/hook',status:'ACTIVE',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}
const subscription={id:'sub-1',eventType:'ai.solution.completed',createdAt:'2026-01-01T00:00:00Z'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
function renderPage(fetchMock:ReturnType<typeof vi.fn>){vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter initialEntries={['/app/app-a/endpoints/endpoint-1']}><Routes><Route path="/app/:applicationId/endpoints/:endpointId" element={<EndpointDetailPage/>}/></Routes></MemoryRouter>)}
afterEach(()=>vi.unstubAllGlobals())

it('sends changed-only PATCH and creates/removes subscriptions through CSRF mutations',async()=>{const fetchMock=vi.fn((url:string,init?:RequestInit)=>{if(url.includes('/auth/csrf'))return Promise.resolve(json({token:'csrf'}));if(url.endsWith('/subscriptions')&&init?.method==='POST')return Promise.resolve(json({id:'sub-2',eventType:'custom.event.created',createdAt:'2026-01-02T00:00:00Z'},201));if(url.includes('/subscriptions/sub-1')&&init?.method==='DELETE')return Promise.resolve(new Response(null,{status:204}));if(url.endsWith('/endpoint-1')&&init?.method==='PATCH')return Promise.resolve(json({...endpoint,...JSON.parse(String(init.body))}));if(url.endsWith('/subscriptions'))return Promise.resolve(json([subscription]));return Promise.resolve(json(endpoint))});renderPage(fetchMock);await screen.findByRole('heading',{name:'Primary endpoint'});fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Renamed endpoint'}});await userEvent.click(screen.getByRole('button',{name:'Save changes'}));expect(await screen.findByText('Endpoint saved.')).toBeInTheDocument();const patch=fetchMock.mock.calls.find(([url,init])=>String(url).endsWith('/endpoint-1')&&(init as RequestInit).method==='PATCH')!;expect((patch[1] as RequestInit).body).toBe(JSON.stringify({name:'Renamed endpoint'}));await userEvent.type(screen.getByLabelText('Event type'),'custom.event.created');const form=screen.getByRole('button',{name:'Add subscription'}).closest('form')!;fireEvent.submit(form);fireEvent.submit(form);expect(await screen.findByText('custom.event.created')).toBeInTheDocument();expect(fetchMock.mock.calls.filter(([url,init])=>String(url).endsWith('/subscriptions')&&(init as RequestInit).method==='POST')).toHaveLength(1);await userEvent.click(screen.getAllByRole('button',{name:'Remove'})[0]);await userEvent.click(screen.getByRole('button',{name:'Remove subscription'}));expect(screen.queryByText('ai.solution.completed')).not.toBeInTheDocument()})

it('handles already-provisioned signing-secret conflict without a reveal',async()=>{const fetchMock=vi.fn((url:string,init?:RequestInit)=>{if(url.includes('/auth/csrf'))return Promise.resolve(json({token:'csrf'}));if(url.endsWith('/signing-secret'))return Promise.resolve(json({code:'SIGNING_SECRET_ALREADY_PROVISIONED',message:'Already provisioned'},409));if(url.endsWith('/subscriptions'))return Promise.resolve(json([]));return Promise.resolve(json(endpoint))});renderPage(fetchMock);await screen.findByRole('heading',{name:'Primary endpoint'});const button=screen.getByRole('button',{name:'Provision signing secret'});fireEvent.click(button);fireEvent.click(button);expect(await screen.findByText('A signing secret is already provisioned for this endpoint.')).toBeInTheDocument();expect(fetchMock.mock.calls.filter(([url])=>String(url).endsWith('/signing-secret'))).toHaveLength(1);expect(screen.queryByText(/whsec_/)).not.toBeInTheDocument()})
